ShakenOrStirred/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace ShakenOrStirred.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

ShakenOrStirred/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ShakenOrStirred.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

ShakenOrStirred/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ShakenOrStirred.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }

}

ShakenOrStirred/Pages/Shaken/Index.cshtml.cs
using Microsoft.AspNetCore.Diagnostics;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using ShakenOrStirred.Model;
using System;
using System.IO;
using System.Net.Http.Headers;
using System.Text;
using System.Text.Json.Nodes;

namespace ShakenOrStirred.Pages.Shaken
{
    public class IndexModel : PageModel
    {
        private readonly ApplicationDbContext _db;

        public IndexModel(ApplicationDbContext db)
        {
            _db = db;
        }

        [BindProperty(SupportsGet = true)]
        public IEnumerable<Drink> Drinks { get; set; }

        public List<Drink> DrinkSet {get; set;}

        [HttpPost]
        public async Task<IActionResult> OnPostLoadSearch()
        {
            // Create a new instance of HttpClient
            using (var HttpClient = new HttpClient())
            {
                // Call the API
                using (HttpResponseMessage response = await HttpClient.GetAsync("http://www.thecocktaildb.com/api/json/v1/1/search.php?api_key=1&s=margarita"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    DrinkList drinkList = JsonConvert.DeserializeObject<DrinkList>(apiResponse);
                    DrinkSet = drinkList.Drinks.ToList();
                    //return new JsonResult(DrinkSet);
                    DeserializeJsonResult(new JsonResult(DrinkSet));
                    return RedirectToPage("/Shaken/Search");
                }

            }

        }
        public List<Drink> DeserializeJsonResult(JsonResult DrinkSet)
        {
            string json = JsonConvert.SerializeObject(DrinkSet.Value);
            List<Drink> drinks = JsonConvert.DeserializeObject<List<Drink>>(json);
            return drinks;
        }

    }
}

ShakenOrStirred/Pages/Shaken/Search.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ShakenOrStirred.Model;

namespace ShakenOrStirred.Pages.Shaken
{
    public class SearchModel : PageModel
    {
        private readonly ApplicationDbContext _db;

        public SearchModel(ApplicationDbContext db)
        {
            _db = db;
        }

        public void OnGet()
        {
            // Instantiate the DeserializeJsonResult function
            //DrinkSet = DeserializeJsonResult(new JsonResult(Drinks));
            //List<Drink> drinks = DeserializeJsonResult((JsonResult)DrinkSet);
        }
    }
}

ShakenOrStirred/Pages/Index.cshtml
@page
@using ShakenOrStirred.Model
@model ShakenOrStirred.Pages.Shaken.IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1>Shaken</h1>
    <h2>This Application is designed with your bar in mind</h2>
    <p>
        How To Use:<br />
        1.) Search by Spirit
    </p>
</div>

<div class="border container" style="padding:30px;">
    <form method="post">
        <div class="text-danger" asp-validation-summary="ModelOnly"></div>
        <div class="form-group row">
            <div class="col-3">
                <label>Drink Name</label>
            </div>
            <div class="col-6">
                <input class="form-control" />
            </div>
        </div>
        <span class="text-danger"></span>
        <div class="form-group row">
            <div class="col-3 offset-3">
                <button  asp-page="/Shaken/Search" asp-page-handler="LoadSearch">Search</button>
            </div>
        </div>
    </form>
 

ShakenOrStirred/Pages/Shaken/Index.cshtml
@page
@model ShakenOrStirred.Pages.Shaken.IndexModel
@{
    ViewData["Title"] = "Index";
}

<br />
<div>
    <p>Test Page<p>
</div>

ShakenOrStirred/Pages/Shaken/Search.cshtml
@page
@using ShakenOrStirred.Model
@model ShakenOrStirred.Pages.Shaken.IndexModel
@{
}



<div class="border container" style="padding:30px;">
    <table class="table">
        <thead>
            <tr>
                <th>Drink Name</th>
                <th>Instructions</th>
                <th>Ingredient</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var d in Model.DrinkSet)
            {
                <tr>
                    <td>@d.strDrink</td>
                    <td>@d.strInstructions</td>
                    <td>@d.strIngredient1</td>
                </tr>
            }
        </tbody>
    </table>
    </div>

ShakenOrStirred/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Shaken</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ShakenOrStirred.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Shaken</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ShakenOrStirred - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>